version: '3.8'

services:
  web:
    build: 
      context: .
      args:
        - SKIP_COLLECTSTATIC=1
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=${DEBUG:-False}
      - PORT=8000
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
      gunicorn --bind 0.0.0.0:8000
      --workers ${WEB_CONCURRENCY:-3}
      --timeout ${GUNICORN_TIMEOUT:-120}
      sopchatbot.wsgi:application"