version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:$PORT --timeout 120 sopchatbot.wsgi:application
    environment:
      DATABASE_URL: ${DATABASE_URL}  # From Render's PostgreSQL or external DB
      SECRET_KEY: ${SECRET_KEY}      # Must be set in Render dashboard
      DEBUG: ${DEBUG:-False}         # Default to False for production
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-.onrender.com}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-https://*.onrender.com}
      # Optional performance tuning:
      WEB_CONCURRENCY: ${WEB_CONCURRENCY:-3}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-120}
    # Render-specific optimizations:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:$PORT/healthcheck/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3