services:
  web:
    build: .
    container_name: sop_app
    command: gunicorn --bind 0.0.0.0:8000 --timeout 120 sopchatbot.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
