services:
  - type: web
    name: sop-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    buildCommand: ""  # leave empty to skip collectstatic during build
    startCommand: gunicorn sopchatbot.wsgi:application --bind 0.0.0.0:8000 --workers 1 --timeout 600
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    postDeploy:
      - python manage.py collectstatic --noinput
      - python manage.py migrate --noinput