# Generated by Django 5.1.7 on 2025-03-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0002_sopinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='sop_docs/')),
                ('reference_count', models.IntegerField(default=0)),
            ],
        ),
    ]
